import { tn, pct } from './formatters';
import { DNA } from '../data/dna';

/**
 * Generate a podcast prep sheet for a matchup.
 * Returns a plain-text string formatted for easy reading on-air.
 */
export function generatePrepSheet(offTm, defTm, oStats, dStats, bl, grade, oRoster, dRoster, playerMatchups) {
  const off = tn(offTm);
  const def = tn(defTm);
  const lines = [];

  lines.push(`═══════════════════════════════════════════════════`);
  lines.push(`PODCAST PREP SHEET — ${off} vs ${def}`);
  lines.push(`Generated by DownfieldOS | downfieldos.com`);
  lines.push(`═══════════════════════════════════════════════════`);
  lines.push(``);

  // Section 1: Opening hook
  lines.push(`▸ OPEN WITH THIS (30 seconds)`);
  lines.push(`─────────────────────────────`);
  const hookGrade = grade === "A+" || grade === "A" ? "favorable" : grade === "F" || grade === "D" ? "unfavorable" : "competitive";
  lines.push(`"${off} vs ${def} grades out as a ${hookGrade} matchup for the offense — ${grade} overall."`);
  lines.push(`${DNA[offTm]?.s || ""}`);
  lines.push(``);

  // Section 2: Key numbers
  lines.push(`▸ KEY NUMBERS (say these on-air)`);
  lines.push(`─────────────────────────────────`);
  lines.push(`${off} pass rate: ${pct(oStats.pr)} ${oStats.pr > bl.pr + 0.05 ? "(pass-heavy)" : oStats.pr < bl.pr - 0.05 ? "(run-heavy)" : "(balanced)"}`);
  lines.push(`${off} success rate: ${pct(oStats.sr)} ${oStats.sr > bl.sr + 0.03 ? "— elite" : oStats.sr < bl.sr - 0.03 ? "— below avg" : "— league avg"}`);
  lines.push(`${off} explosive rate: ${pct(oStats.xr)} (league avg: ${pct(bl.xr)})`);
  lines.push(`${def} success rate allowed: ${pct(dStats.dsr)} ${dStats.dsr > bl.sr + 0.02 ? "— leaky" : dStats.dsr < bl.sr - 0.02 ? "— stingy" : "— avg"}`);
  lines.push(`${def} explosive rate allowed: ${pct(dStats.dxr)}`);
  lines.push(``);

  // Section 3: Talking points
  lines.push(`▸ TALKING POINTS (2-3 minutes)`);
  lines.push(`──────────────────────────────`);

  // Point 1: Schematic edge
  if (oStats.pr > 0.58 && dStats.dsr > bl.sr + 0.02) {
    lines.push(`1. SCHEMATIC EDGE: ${off} wants to throw and ${def} can't stop the pass. This is a bad matchup for ${def}.`);
  } else if (oStats.xr > bl.xr + 0.02 && dStats.dxr > bl.xr + 0.02) {
    lines.push(`1. EXPLOSIVE ALERT: ${off} generates big plays and ${def} gives them up. Expect fireworks.`);
  } else if (oStats.sr > bl.sr + 0.03 && dStats.dsr < bl.sr - 0.02) {
    lines.push(`1. UNSTOPPABLE VS. IMMOVABLE: ${off}'s efficiency meets ${def}'s stingy defense. Something has to give.`);
  } else {
    lines.push(`1. EVEN MATCHUP: No clear schematic edge. This one comes down to execution and who wins at the line of scrimmage.`);
  }

  // Point 2: Player matchup to watch
  if (playerMatchups && playerMatchups.length > 0) {
    const best = playerMatchups.reduce((a, b) => Math.abs(a.off.rating - a.def.rating) > Math.abs(b.off.rating - b.def.rating) ? a : b);
    const edge = best.off.rating - best.def.rating;
    lines.push(`2. MATCHUP TO WATCH: ${best.off.name} vs ${best.def.name} (${best.label}). ${edge > 10 ? "Big advantage offense." : edge < -10 ? "Defense wins this one." : "Could go either way."}`);
  }

  // Point 3: Contrarian take
  if (oStats.sr < bl.sr && oStats.xr > bl.xr + 0.02) {
    lines.push(`3. CONTRARIAN TAKE: ${off} isn't efficient, but they're explosive. They'll look bad for three drives then rip off a 50-yarder. Don't panic if the start is ugly.`);
  } else if (dStats.dsr > bl.sr + 0.03 && dStats.dxr < bl.xr - 0.01) {
    lines.push(`3. CONTRARIAN TAKE: ${def}'s defense gives up yardage but not big plays. ${off} will have to sustain long drives, which is harder than it sounds.`);
  } else if (oStats.pr < 0.48 && oStats.sr > bl.sr + 0.02) {
    lines.push(`3. CONTRARIAN TAKE: ${off} is run-heavy but efficient. In an era where everyone throws, they win by controlling the clock and staying on schedule.`);
  } else {
    lines.push(`3. CONTRARIAN TAKE: The grade says ${grade}, but watch the turnover battle. In even matchups, the team that protects the ball wins 70% of the time.`);
  }
  lines.push(``);

  // Section 4: Fantasy quick hits
  lines.push(`▸ FANTASY QUICK HITS (60 seconds)`);
  lines.push(`──────────────────────────────────`);
  const qb = oRoster?.offense?.find(p => p.pos === "QB");
  const wr1 = oRoster?.offense?.find(p => p.pos === "WR1");
  const rb1 = oRoster?.offense?.find(p => p.pos === "RB1");
  if (qb) lines.push(`QB ${qb.name}: ${dStats.dsr > bl.sr + 0.02 ? "SMASH — soft defense, volume expected" : dStats.dsr < bl.sr - 0.02 ? "FADE — tough defense, lower ceiling" : "Solid start, standard projection"}`);
  if (wr1) lines.push(`WR ${wr1.name}: ${oStats.pr > 0.55 && dStats.dxr > bl.xr ? "BOOM candidate — deep shots likely" : "Standard usage expected"}`);
  if (rb1) lines.push(`RB ${rb1.name}: ${oStats.pr < 0.52 ? "WORKHORSE — heavy volume game script" : dStats.dsr > bl.sr + 0.03 ? "Sneaky play — weak run defense" : "Typical workload"}`);
  lines.push(``);

  // Section 5: One-liner summary
  lines.push(`▸ CLOSE WITH THIS`);
  lines.push(`──────────────────`);
  const projection = oStats.sr > dStats.dsr + 0.03 ? `${off} should move the ball. Lean offense.` : dStats.dsr < oStats.sr - 0.03 ? `${def}'s defense should hold. Lean under.` : `Coin flip. Watch the trenches.`;
  lines.push(`"Bottom line: ${projection}"`);
  lines.push(``);
  lines.push(`═══════════════════════════════════════════════════`);
  lines.push(`Powered by DownfieldOS — downfieldos.com`);
  lines.push(`═══════════════════════════════════════════════════`);

  return lines.join("\n");
}

/**
 * Generate a newsletter draft for a matchup.
 * Returns markdown-formatted text ready to paste into an email editor.
 */
export function generateNewsletterDraft(offTm, defTm, oStats, dStats, bl, grade, oRoster, dRoster) {
  const off = tn(offTm);
  const def = tn(defTm);
  const lines = [];

  lines.push(`# ${off} vs ${def} — Matchup Preview`);
  lines.push(`*Matchup Grade: **${grade}***`);
  lines.push(``);

  // Opening paragraph
  const hookStyle = oStats.pr > 0.58 ? "pass-heavy" : oStats.pr < 0.48 ? "run-heavy" : "balanced";
  lines.push(`## The Setup`);
  lines.push(`${off} brings a ${hookStyle} offense into this one (${pct(oStats.pr)} pass rate). ${DNA[offTm]?.s || ""} On the other side, ${def}'s defense is allowing a ${pct(dStats.dsr)} success rate ${dStats.dsr > bl.sr + 0.02 ? "— one of the worst marks in the league" : dStats.dsr < bl.sr - 0.02 ? "— one of the best in football" : "— right around league average"}.`);
  lines.push(``);

  // Key numbers
  lines.push(`## By the Numbers`);
  lines.push(`| Stat | ${off} OFF | ${def} DEF | Edge |`);
  lines.push(`|------|-----------|-----------|------|`);
  const srEdge = oStats.sr - dStats.dsr;
  lines.push(`| Success Rate | ${pct(oStats.sr)} | ${pct(dStats.dsr)} | ${srEdge > 0.02 ? off : srEdge < -0.02 ? def : "Even"} |`);
  const xrEdge = oStats.xr - dStats.dxr;
  lines.push(`| Explosive Rate | ${pct(oStats.xr)} | ${pct(dStats.dxr)} | ${xrEdge > 0.01 ? off : xrEdge < -0.01 ? def : "Even"} |`);
  lines.push(`| Pass Rate | ${pct(oStats.pr)} | ${pct(dStats.dpr)} faced | — |`);
  lines.push(``);

  // The edge
  lines.push(`## The Edge`);
  if (oStats.xr > bl.xr + 0.02 && dStats.dxr > bl.xr + 0.02) {
    lines.push(`Explosive offense meets porous defense. ${off} generates big plays at a ${pct(oStats.xr)} clip, and ${def} allows them at ${pct(dStats.dxr)}. This is a recipe for chunk plays and points.`);
  } else if (oStats.sr > bl.sr + 0.03 && dStats.dsr < bl.sr - 0.02) {
    lines.push(`Efficient offense vs. elite defense — the classic clash. ${off} stays on schedule (${pct(oStats.sr)} success rate), but ${def} only allows ${pct(dStats.dsr)}. Something has to give.`);
  } else {
    lines.push(`No clear schematic advantage for either side. This one comes down to execution, turnover margin, and which team wins the line of scrimmage.`);
  }
  lines.push(``);

  // Bottom line
  lines.push(`## Bottom Line`);
  const proj = oStats.sr > dStats.dsr + 0.03 ? `Lean ${off}. The offense has the efficiency edge.` : dStats.dsr < oStats.sr - 0.03 ? `Lean ${def}'s defense. They have the tools to slow this down.` : `Coin flip. The margin is razor-thin.`;
  lines.push(proj);
  lines.push(``);
  lines.push(`---`);
  lines.push(`*Generated by [DownfieldOS](https://downfieldos.com) — Football, understood.*`);

  return lines.join("\n");
}
