name: Data - Availability

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: data-availability-test
  cancel-in-progress: false

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: echo "same name as broken, but different filename"
