import { useMemo } from "react";
import games2026 from "../../data/games2026.json";
import { tn } from "../../utils/formatters";

// Compact per-game recap card grid. Reads the game-recap feed generated by
// scripts/build-games-2026.js (schedules/games.csv + local PBP). Every field
// on the card is data — score, margin shape, total shape, one deterministic
// narrative line. Editorial recaps live in the newsletter, not the site.
export function WeekRecaps({ week, showEmpty = true, highlightTeam = null, compact = false }) {
  const games = useMemo(() => {
    const rows = games2026.games || [];
    return rows.filter(g => g.week === week);
  }, [week]);

  const played = games.filter(g => g.played);
  const scheduled = games.filter(g => !g.played);

  if (!games.length && !showEmpty) return null;

  const cardStyle = {
    background: "#0d1117",
    border: "1px solid #21262d",
    borderRadius: 12,
    padding: compact ? 12 : 16,
    minHeight: compact ? 90 : 110,
  };

  const Card = ({ g }) => {
    const isHighlighted = highlightTeam && (g.home === highlightTeam || g.away === highlightTeam);
    return (
      <div style={{
        ...cardStyle,
        borderColor: isHighlighted ? "#f97316" : "#21262d",
      }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
          <div style={{ fontSize: 11, color: "#8b949e", fontFamily: "monospace", textTransform: "uppercase", letterSpacing: 1 }}>
            {g.weekday?.slice(0, 3)} · {g.date}
          </div>
          {g.played ? (
            <div style={{ fontSize: 10, color: "#22c55e", fontWeight: 700, textTransform: "uppercase", letterSpacing: 1 }}>
              Final{g.overtime ? " (OT)" : ""}
            </div>
          ) : (
            <div style={{ fontSize: 10, color: "#8b949e", fontWeight: 700, textTransform: "uppercase", letterSpacing: 1 }}>
              {g.gametime || "Scheduled"}
            </div>
          )}
        </div>

        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 8 }}>
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 14, fontWeight: 800, color: g.played && g.winner === g.away ? "#f0f6fc" : "#8b949e", fontFamily: "monospace" }}>
              {g.away}
              {g.played && <span style={{ marginLeft: 8, color: g.winner === g.away ? "#22c55e" : "#8b949e" }}>{g.away_score}</span>}
            </div>
            <div style={{ fontSize: 11, color: "#8b949e", marginTop: 2 }}>{tn(g.away)}</div>
          </div>
          <div style={{ padding: "0 12px", color: "#484f58", fontSize: 12 }}>@</div>
          <div style={{ flex: 1, textAlign: "right" }}>
            <div style={{ fontSize: 14, fontWeight: 800, color: g.played && g.winner === g.home ? "#f0f6fc" : "#8b949e", fontFamily: "monospace" }}>
              {g.played && <span style={{ marginRight: 8, color: g.winner === g.home ? "#22c55e" : "#8b949e" }}>{g.home_score}</span>}
              {g.home}
            </div>
            <div style={{ fontSize: 11, color: "#8b949e", marginTop: 2 }}>{tn(g.home)}</div>
          </div>
        </div>

        {g.played && !compact && (
          <div style={{ fontSize: 11, color: "#c9d1d9", lineHeight: 1.4, borderTop: "1px solid #21262d", paddingTop: 8 }}>
            {g.narrative}
          </div>
        )}
      </div>
    );
  };

  return (
    <div>
      {played.length > 0 && (
        <div style={{ marginBottom: scheduled.length ? 20 : 0 }}>
          <div style={{ fontSize: 11, fontWeight: 800, color: "#22c55e", textTransform: "uppercase", letterSpacing: 2, marginBottom: 12 }}>
            Week {week} — Results · {played.length} game{played.length === 1 ? "" : "s"}
          </div>
          <div style={{ display: "grid", gridTemplateColumns: compact ? "1fr 1fr" : "repeat(auto-fill, minmax(280px, 1fr))", gap: 12 }}>
            {played.map(g => <Card key={g.gameId} g={g} />)}
          </div>
        </div>
      )}
      {scheduled.length > 0 && (
        <div>
          <div style={{ fontSize: 11, fontWeight: 800, color: "#f97316", textTransform: "uppercase", letterSpacing: 2, marginBottom: 12 }}>
            Week {week} — Upcoming · {scheduled.length} game{scheduled.length === 1 ? "" : "s"}
          </div>
          <div style={{ display: "grid", gridTemplateColumns: compact ? "1fr 1fr" : "repeat(auto-fill, minmax(280px, 1fr))", gap: 12 }}>
            {scheduled.map(g => <Card key={g.gameId} g={g} />)}
          </div>
        </div>
      )}
      {!games.length && (
        <div style={{ fontSize: 12, color: "#8b949e" }}>No games for Week {week}.</div>
      )}
      <div style={{ fontSize: 10, color: "#484f58", marginTop: 12, fontStyle: "italic" }}>
        Source: nflverse schedules + PBP · updated {new Date(games2026.generated_at).toLocaleString()}
      </div>
    </div>
  );
}
